---
title: "Sediment_2017"
author: "Tiff Stephens"
date: "12/1/2017"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Libraries, echo = FALSE, include=FALSE}
library(dplyr); library(tidyr); library(ggplot2)
theme_set(theme_classic())
```

Import data
```{r}
# datachunk: TAS

cr.mat <- read.csv("https://raw.githubusercontent.com/APECS-ak/sediment_2017/master/RAW_core_matter.csv", stringsAsFactors = FALSE, header = TRUE)
```


Look at data
```{r}
str(cr.mat)

nrow(cr.mat)

```



# Cleaning Data for Analysis

Calculate dry weights, organic matter, inorganic matter
```{r}
# datachunk: TAS


# piped calculations for all
cr.mat = cr.mat %>% 
  mutate(sed_ww_pre_60C = pan_sediment_ww_pre_60C - pan_weight, na.rm = TRUE) %>%
  mutate(sed_dw_post_60C = pan_sediment_dw_post_60C - pan_weight, na.rm = TRUE) %>%
  mutate(dry_bulk_density = sed_dw_post_60C / sample_volume, na.rm = TRUE) %>%
  mutate(sed_dw_pre_450C = pan_sediment_dw_pre_450C - pan_weight, na.rm = TRUE) %>%
  mutate(sed_dw_post_450C = pan_sediment_dw_post450C - pan_weight, na.rm = TRUE) %>%
  mutate(om_weight = sed_dw_pre_450C - sed_dw_post_450C, na.rm = TRUE) %>%
  mutate(sed_dw_pre_950C = crucible_sediment_dw_pre_950C - crucible_weight, na.rm = TRUE) %>%
  mutate(sed_dw_post_950C = crucible_sediment_dw_post_950C - crucible_weight, na.rm = TRUE) %>%
  mutate(im_weight = sed_dw_pre_950C - sed_dw_post_950C) %>%
  mutate(percent_om = (om_weight / sed_dw_pre_450C) * 100, na.rm = TRUE) %>%
  mutate(percent_im = (im_weight / sed_dw_pre_950C) * 100, na.rm = TRUE) %>%
  mutate(om.im_ratio = om_weight / im_weight, na.rm = TRUE) %>%
  mutate(om_density = om_weight * dry_bulk_density, na.rm = TRUE) %>%
  mutate(im_density = im_weight * dry_bulk_density, na.rm = TRUE)
  

# check new column names
colnames(cr.mat)


# remove pan and crucible combo weights (not necessary for analysis) 
#cr.mat = cr.mat %>% 
  #select(-pan_weight, -pan_sediment_ww_pre_60C, -pan_sediment_dw_post_60C, -pan_sediment_dw_pre_450C, -pan_sediment_dw_post450C, -crucible_weight, -crucible_sediment_dw_pre_950C, -crucible_sediment_dw_post_950C, -sed_dw_post_60C, -sed_ww_pre_60C, -sed_dw_post_450C, -sed_dw_post_450C, -sed_dw_post_950C, -sed_dw_pre_950C, -layer_volume)
```


```{r}
write.csv(cr.mat,'CLEAN_core_matter.csv')
```



# READ CLEAN FILE

```{r}
cr.mat <- read.csv("https://raw.githubusercontent.com/APECS-ak/sediment_2017/master/CLEAN_core_matter.csv", stringsAsFactors = FALSE, header = TRUE)
```


```{r}
library(DT)


cr.mat_noL06 = cr.mat[-c(1:30),]

cr.mat_noL06$otter_region=factor(cr.mat_noL06$otter_region, levels=c("Low","Mid","High"))



ggplot(cr.mat_noL06, aes(layer_number, om_density)) +
  stat_summary(fun.y=mean, geom="point", position="dodge")+
  stat_summary(fun.data=mean_se, geom="errorbar", position=position_dodge(width=0.90), width=0.2) +
  coord_flip() +
  #geom_errorbar(aes(xmin=om_density-se, ymax=len+se), colour="black", width=.1) +
  facet_wrap(~otter_region, ncol = 1)
```










