---
title: "Preliminary Results"
author: "Tiff Stephens"
date: "12/1/2017"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
library(dplyr); library(tidyr); library(ggplot2); library(DT); library(cowplot); library(leaflet)
theme_set(theme_classic())
```

#Importing cleaned .csv file and looking at dataframe
```{r}
# read clean file from github
cr.mat <- read.csv("https://raw.githubusercontent.com/APECS-ak/sediment_2017/master/CLEAN_core_matter.csv", stringsAsFactors = FALSE, header = TRUE)

# check 
str(cr.mat)
```

#Remove excess columns (e.g. pan + crucible data recorded prior to final calcualted weights)
```{r}

# remove pan, crucible, and sediment combo weights not necessary for analysis
cr.mat = cr.mat %>% 
  select(-na.rm, -pan_number, -pan_weight, -pan_sed_ww_pre_60C, -pan_sed_dw_post_60C, -pan_sed_dw_pre_450C, -pan_sed_dw_post450C, -crucible_weight, -crucible_sed_dw_pre_950C, -crucible_sed_dw_post_950C, -sed_ww_pre_60C, -sed_dw_post_60C, -sed_dw_pre_450C, -sed_dw_post_450C, -sed_dw_pre_950C, -sed_dw_post_950C)


colnames(cr.mat)
```



# Plotting
## Grouped by sea otter zone
```{r fig1, fig.height = 10, fig.width = 8, echo = FALSE, warning = FALSE}


cr.mat_noL06 = cr.mat[-c(1:30),] # remove L06 (for now) because organic matter is off the scale

cr.mat_noL06$otter_region=factor(cr.mat_noL06$otter_region, levels=c("Low","Mid","High")) # order zones


# plot organic matter
plot_om = ggplot(cr.mat_noL06, aes(layer_number, om_density)) +
  stat_summary(fun.y=mean, geom="point")+
  stat_summary(fun.data=mean_se, geom="errorbar", width=0.5) +
  coord_flip() +
  scale_x_reverse() +
  xlab("Core Depth") +
  ylab("Organic Matter (g cm^3)") +
  #scale_x_continuous(position = "top") +
  #scale_y_continuous(position = "left") +
  facet_wrap(~otter_region, ncol = 1)

#plopt inorganic matter
plot_im = ggplot(cr.mat_noL06, aes(layer_number, im_density)) +
  stat_summary(fun.y=mean, geom="point")+
  stat_summary(fun.data=mean_se, geom="errorbar", width=0.5) +
  coord_flip() +
  scale_x_reverse() +
  xlab("Core Depth") +
  ylab("Inorganic Matter (g cm^3)") +
  #scale_x_continuous(position = "top") +
  #scale_y_continuous(position = "left") +
  facet_wrap(~otter_region, ncol = 1)

# organize om and im side-by-side
plot_grid(plot_om, plot_im, align = "hv", ncol = 2)
```

# Mapping
## From which sites have cores been processed and data entered? 
```{r, echo = FALSE, message = FALSE}
locations = cr.mat_noL06 %>%
  distinct(cr.mat_noL06, latitude, longitude) %>%
  drop_na()



# turn into leaflet map

leaflet(locations) %>%
  addTiles() %>%
  addMarkers(~longitude, ~latitude, popup = ~cr.mat_noL06$site)
```


